name: Run Rqalpha Backtest with conda

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.9
      uses: s-weigand/setup-conda@v1

    - run: conda --version
    - run: which python

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0