name: Run Rqalpha Backtest with conda

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install sshpass

    - name: Set up conda
      uses: s-weigand/setup-conda@v1
    - run: conda --version
    - run: which python
    - run: source activate base

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install rqalpha pandas TA-Lib
        rqalpha download-bundle


    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0