name: Run Rqalpha Backtest with Conda

on:
  workflow_dispatch:
    inputs:
      strategy_category:
        description: 'strategy category'
        required: true
        default: 'rotation_strategy'
      strategy_name:
        description: 'strategy name'
        required: true
        default: 'rs_smae_style_28'
      backtest_type:
        description: 'param_optimize or period_test'
        required: true
        default: 'param_optimize'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install sshpass

    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      
    - run: conda --version
    - run: which python
    - run: source activate base

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install rqalpha pandas
        conda install -c conda-forge ta-lib
        rqalpha download-bundle

    - name: Run backtest python file
      run: |
        if [ ! -d ./backtest/${{ github.event.inputs.strategy_category }}/bt_report/${{ github.event.inputs.strategy_name }}/${{ github.event.inputs.backtest_type }} ]; then
          mkdir -p ./backtest/${{ github.event.inputs.strategy_category }}/bt_report/${{ github.event.inputs.strategy_name }}/${{ github.event.inputs.backtest_type }}
        else
          rm -rf ./backtest/${{ github.event.inputs.strategy_category }}/bt_report/${{ github.event.inputs.strategy_name }}/${{ github.event.inputs.backtest_type }}/*
        fi
        export PYTHONPATH=$PYTHONPATH:$PWD
        python -u ./backtest/${{ github.event.inputs.strategy_category }}/bt/${{ github.event.inputs.strategy_name }}/${{ github.event.inputs.strategy_name }}_${{ github.event.inputs.backtest_type }}.py
    
    - name: Upload report to Home Server
      run: |
        sshpass -p ${{ secrets.HOME_SERVER_PASS }} scp -P ${{ secrets.HOME_SERVER_PORT }} -o StrictHostKeyChecking=no ./backtest/${{ github.event.inputs.strategy_category }}/bt_report/${{ github.event.inputs.strategy_name }}/${{ github.event.inputs.backtest_type }}/*.xlsx ${{ secrets.HOME_SERVER_USERNAME }}@${{ secrets.HOME_SERVER_ADDRESS }}:/home/layewang/Downloads
